# Makes a multilib image's install list name multilib packages; added only for a multilib profile.

BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-wk-multilib"
BBFILE_PATTERN_meta-wk-multilib = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-wk-multilib = "10"

LAYERDEPENDS_meta-wk-multilib = "core"
LAYERSERIES_COMPAT_meta-wk-multilib = "scarthgap"
