#!/bin/bash

export BUILDDIR="$HOME/Development/ReleaseVersion/OpenSource"
export CONFIG="Release"
export PATH=$HOME/bin:$BUILDDIR/Tools/Scripts:$BUILDDIR/Tools/Scripts:${HOME}/.jsvu:/$HOME/wabt/bin/:$PATH
cd $BUILDDIR
