#!/bin/bash

export BUILDDIR="/home/justin/WebKit/ReleaseVersion/OpenSource"
export CONFIG="Release"
export PATH=$HOME/bin:$BUILDDIR/Tools/Scripts:$BUILDDIR/../Internal/Tools/Scripts:$PATH
cd $BUILDDIR
