#!/bin/bash

cd $BUILDDIR

echo $BUILDDIR

if [[ "$CONFIG" == "Release" ]]
then
    echo "Building release"
    ./Tools/Scripts/set-webkit-configuration --release
    ./Tools/Scripts/build-webkit --release --export-compile-commands --jsc-only --fuse-ld=mold | filter-build-webkit
else
    echo "Building debug"
    ./Tools/Scripts/set-webkit-configuration --debug --no-asan
    ./Tools/Scripts/build-webkit --jsc-only --debug --export-compile-commands --cmakeargs="-DUSE_LIBBACKTRACE=yes" --fuse-ld=mold -DDEVELOPER_MODE=ON | filter-build-webkit
fi
