#!/bin/bash

cd $BUILDDIR

echo $BUILDDIR

MACHINE_BITS=`getconf LONG_BIT`
MACHINE_ARCH=$(uname -m)

if [[ $MACHINE_BITS == "32" ]]; then
    MACHINE_ARGS=(--32-bit)
elif [[ $MACHINE_ARCH == "aarch64" || $MACHINE_ARCH == "arm64" ]]; then
    MACHINE_ARGS=(--cmakeargs="-DCMAKE_C_FLAGS='-moutline-atomics' -DCMAKE_CXX_FLAGS='-moutline-atomics'")
else
    # x86_64 — no special flags needed
    MACHINE_ARGS=()
fi

if [[ "$CONFIG" == "Release" ]]
then
    echo "Building release"
    ./Tools/Scripts/set-webkit-configuration --release --no-asan
    ./Tools/Scripts/build-webkit --release --export-compile-commands --jsc-only --no-use-ccache --generate-project-only --cmakeargs="-DUSE_LIBBACKTRACE=OFF -DDEVELOPER_MODE=ON -DENABLE_OFFLINE_ASM_ALT_ENTRY=0" "${MACHINE_ARGS[@]}" "$@" | filter-build-webkit
    ln -s -f WebKitBuild/JSCOnly/Release/compile_commands.json compile_commands.json
else
    echo "Building debug"
    ./Tools/Scripts/set-webkit-configuration --debug --no-asan
    ./Tools/Scripts/build-webkit --no-fatal-warnings --debug --export-compile-commands --jsc-only --no-use-ccache --generate-project-only --cmakeargs="-DENABLE_JSC_GLIB_API=ON -DUSE_LIBBACKTRACE=ON -DDEVELOPER_MODE=ON -DENABLE_OFFLINE_ASM_ALT_ENTRY=1" "${MACHINE_ARGS[@]}" "$@" | filter-build-webkit
    ln -s -f WebKitBuild/JSCOnly/Debug/compile_commands.json compile_commands.json
    echo "Done"
fi
