#!/bin/bash

cd $BUILDDIR

echo $BUILDDIR

if [[ "$CONFIG" == "Release" ]]
then
    cd WebKitBuild/JSCOnly/Release/ && time ninja -k 0 -j`echo $jobs` jsc
else
    cd WebKitBuild/JSCOnly/Debug/ && time ninja -k 0 -j`echo $jobs` jsc
fi
