#!/bin/bash
echo '-1' | sudo tee /proc/sys/kernel/perf_event_paranoid
export VM=$BUILDDIR/WebKitBuild/JSCOnly/$CONFIG/
JSC_validateOptions=1 LD_LIBRARY_PATH=$VM ~/Development/samply/target/release/samply record $VM/bin/jsc --useJITDump=1 --useTextMarkers=1 --exposeProfilersOnGlobalObject=1 --alwaysComputeHash=1 "$@"
