NSGlobalDomain AppleInterfaceStyle string Dark

NSGlobalDomain AppleShowAllExtensions bool true

NSGlobalDomain AppleKeyboardUIMode int 2

NSGlobalDomain NSAutomaticSpellingCorrectionEnabled bool false
NSGlobalDomain NSAutomaticCapitalizationEnabled bool false
NSGlobalDomain NSAutomaticDashSubstitutionEnabled bool false
NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled bool false
NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled bool false

NSGlobalDomain com.apple.mouse.scaling float 0.5

NSGlobalDomain AppleICUForce24HourTime bool true

NSGlobalDomain AppleWindowTabbingMode string always

com.apple.dock show-recents bool false
com.apple.dock mru-spaces bool false

# wvous corner values: 1 = do nothing, 2 = Mission Control.
com.apple.dock wvous-br-corner int 1
com.apple.dock wvous-tl-corner int 2

com.apple.screensaver askForPassword int 0

com.apple.Safari IncludeDevelopMenu bool true
com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey bool true
