"""lib/wk/sshalias.py writes the `Host wk-<name>` block byte for byte, takes it
out leaving every other host, and refuses an empty HostName or User, since ssh
would refuse the whole file and every host in it.

Run: python3 tests/run.py -k tests.test_wk_sshalias
"""
import io
import os
import sys
import tempfile
import unittest
from contextlib import redirect_stderr
from unittest import mock

from tests.support import REPO

sys.path.insert(0, str(REPO / "lib"))
from wk import machine, sshalias  # noqa: E402
from wk.act import Refused  # noqa: E402

OTHERS = "Host other\n    HostName 1.2.3.4\n\nHost wk-demo\n    HostName old\n    User old\n\nHost tail\n    User t\n"
BLOCK = "\nHost wk-demo\n    # generated by wk -- removed by wk rm\n    HostName %s\n    User %s\n    StrictHostKeyChecking no\n" \
        "    UserKnownHostsFile /dev/null\n%s\n"
CASES = (
    ("plain", ("demo", "10.0.0.1", "admin"), {}, "", BLOCK % ("10.0.0.1", "admin", "")),
    ("identity_and_extra", ("demo", "10.0.0.2", "root"), {"identity": "/k/id", "extra": ("ProxyJump gw", "Port 2222")}, "",
     BLOCK % ("10.0.0.2", "root", "    IdentityFile /k/id\n    IdentitiesOnly yes\n    ProxyJump gw\n    Port 2222")),
    ("extra_alone", ("demo", "10.0.0.4", "u"), {"extra": ("Port 22",)}, "", BLOCK % ("10.0.0.4", "u", "\n    Port 22")),
    ("replacing", ("demo", "10.0.0.3", "u"), {}, OTHERS,
     "Host other\n    HostName 1.2.3.4\n\nHost tail\n    User t\n" + BLOCK % ("10.0.0.3", "u", "")),
    ("removing", None, {}, OTHERS, "Host other\n    HostName 1.2.3.4\n\nHost tail\n    User t\n"),
)


class TestOnDisk(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.mkdtemp(prefix="wk-test-sshalias-")
        self.addCleanup(machine.Local().remove, self.tmp)

    def test_every_block_is_the_one_ssh_reads_byte_for_byte_in_a_private_directory(self):
        local = machine.Local()
        for case, args, kw, before, want in CASES:
            env = {"HOME": os.path.join(self.tmp, case)}
            if before:
                os.makedirs(os.path.dirname(sshalias.alias_path(env)))
                with open(sshalias.alias_path(env), "w") as f:
                    f.write(before)
            if args is None:
                sshalias.alias_remove(local, env, "demo")
            else:
                sshalias.alias_set(local, env, *args, **kw)
            with self.subTest(case=case), open(sshalias.alias_path(env)) as f:
                self.assertEqual(want, f.read())
        d = os.path.dirname(sshalias.alias_path({"HOME": os.path.join(self.tmp, "plain")}))
        self.assertEqual("0o700", oct(os.stat(d).st_mode & 0o777))


class TestOnTheFake(unittest.TestCase):
    def setUp(self):
        self.fake = machine.Fake("box")
        self.fake.answer(["chmod"])
        self.env = {"HOME": "/home/u"}
        self.conf = sshalias.alias_path(self.env)
        self.flags = mock.patch.dict(os.environ, {}, clear=False)
        self.flags.start()
        self.addCleanup(self.flags.stop)
        os.environ.pop("WK_DRY_RUN", None)

    def stderr(self, fn):
        buf = io.StringIO()
        with redirect_stderr(buf):
            fn()
        return buf.getvalue()

    def test_no_address_or_user_is_refused_with_the_words_bash_uses_and_nothing_is_written(self):
        for hostname, user in (("", "admin"), ("10.0.0.1", "")):
            err = self.stderr(lambda: self.assertRaises(
                Refused, sshalias.alias_set, self.fake, self.env, "demo", hostname, user))
            self.assertIn("no address for 'demo', so no ssh alias was written: an empty HostName\n"
                          "    makes ssh refuse to read %s at all, and with it every other host in it" % self.conf, err)
        self.assertEqual(self.fake.effects, [])

    def test_the_directory_is_made_private_once(self):
        sshalias.alias_set(self.fake, self.env, "a", "10.0.0.1", "u")
        d = os.path.dirname(self.conf)
        self.assertEqual(self.fake.effects, [("mkdir", d), ("run", ("chmod", "0700", d)), ("write", self.conf)])
        sshalias.alias_set(self.fake, self.env, "b", "10.0.0.2", "u")
        self.assertEqual(self.fake.effects[3:], [("write", self.conf)])
        self.assertEqual(self.fake.files[self.conf].count("Host wk-"), 2)

    def test_a_directory_that_cannot_be_made_private_is_a_refusal(self):
        self.fake.answer(["chmod"], rc=1, err="chmod: not permitted")
        err = self.stderr(lambda: self.assertRaises(
            Refused, sshalias.alias_set, self.fake, self.env, "a", "10.0.0.1", "u"))
        self.assertIn("cannot set mode 0700 on %s" % os.path.dirname(self.conf), err)

    def test_removing_an_absent_block_writes_nothing(self):
        sshalias.alias_remove(self.fake, self.env, "demo")
        self.fake.files[self.conf] = "Host other\n    HostName 1.2.3.4\n"
        sshalias.alias_remove(self.fake, self.env, "demo")
        self.assertEqual(self.fake.effects, [])
        sshalias.alias_remove(self.fake, self.env, "other")
        self.assertEqual(self.fake.effects, [])

    def test_removing_takes_only_the_named_block(self):
        self.fake.files[self.conf] = OTHERS
        sshalias.alias_remove(self.fake, self.env, "demo")
        self.assertEqual(self.fake.files[self.conf], "Host other\n    HostName 1.2.3.4\n\nHost tail\n    User t\n")

    def test_a_dry_run_writes_nothing(self):
        os.environ["WK_DRY_RUN"] = "1"
        self.fake.files[self.conf] = OTHERS
        self.fake.dirs.add(os.path.dirname(self.conf))
        sshalias.alias_set(self.fake, self.env, "demo", "10.0.0.9", "u")
        self.assertEqual(self.fake.files[self.conf], OTHERS)
        self.assertEqual([e[0] for e in self.fake.effects], ["write"])


if __name__ == "__main__":
    unittest.main()
