theme = "catppuccin_mocha"

[keys.insert]
S-tab = "unindent"

[editor]
true-color = true

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.auto-save]
after-delay.enable = true
after-delay.timeout = 3000

