theme = "catppuccin_mocha"

[editor.soft-wrap]
enable = true

[editor.lsp]
display-inlay-hints = true

[keys.insert]
S-tab = "unindent"
tab = "indent"

[keys.select]
S-tab = "unindent"
tab = "indent"


[keys.normal]
S-tab = "unindent"
tab = "indent"

[editor]
true-color = true

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.auto-save]
after-delay.enable = true
after-delay.timeout = 3000

