[language-server.solargraph]
config.diagnostics=false
config.formatting=false

[[language]]
name = "ruby"
auto-format = false
language-servers=[{name="solargraph"}]

[language-server.clangd]
command = "clangd"
args = ["--header-insertion=never"]

[[language]]
name = "cpp"
language-servers = ["clangd"]
roots = [".git", "CMakeLists.txt"]
