#!/bin/sh
# BusyBox init: S41 runs wk-wifi-join once, after S40network has eth0 up.

start() {
    [ -x /usr/sbin/wk-wifi-join ] && /usr/sbin/wk-wifi-join
    return 0
}

stop() {
    return 0
}

case "$1" in
    start) start ;;
    stop)  stop ;;
    restart|reload) stop; start ;;
    *) echo "Usage: $0 {start|stop|restart}"; exit 1 ;;
esac
