"""`wk completion bash|zsh`, generated from the declarations, never `-h` text; build presets
from lib/wk/presets.py; workspace names and `values=` lists are asked at TAB, of this machine only."""

import os
import sys

from wk import images, presets
from wk import decl as D
from wk.places import Registry

BUILTIN_COMMANDS = ("completion",)
SHELLS = ("bash", "zsh")
LOCAL_WHERE = ("local", "host")


def local_workspaces(root, env=None):
    return Registry(root, env).local_workspaces()


def flags_for(d, verb=None):
    """The options of one verb, or of a command with none."""
    specs = [d.opts_for([verb])] if verb else [d.opts] + [spec.get("opts") for _, spec in d.flag]
    return sorted({x.rstrip("=") for spec in specs for x in (spec or "").split(",") if x})


def subverbs(d):
    return sorted(filter(None, d.verbs.split(",")))


def values_cmd(d):
    """The `values=` argument, when the flag it names runs on this machine; a store or workspace one would reach a machine at TAB."""
    if not d.values:
        return ""
    where = d.where
    for flags, spec in d.flag:
        if d.values in flags.split(","):
            where = spec.get("where", where)
    return d.values if where in LOCAL_WHERE else ""


def commands(root):
    return sorted({d.name for d in D.all_commands(root)} | set(BUILTIN_COMMANDS))


def _words(words):
    return "'%s'" % " ".join(words)


_FUNCTION = r'''
_wk_completion() {
    local cur prev bin cmd i typed=0 words= first= verb= slot shift=0
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    bin="${COMP_WORDS[0]}"
    if [ "$COMP_CWORD" -eq 1 ]; then
        COMPREPLY=( $(compgen -W "$_wk_commands" -- "$cur") )
        return 0
    fi
    cmd="${COMP_WORDS[1]}"
    _wk_decl "$cmd" || return 0
    if [ "$prev" = --preset ] && [ "$_wk_preset" = --preset ]; then
        COMPREPLY=( $(compgen -W "$_wk_presets" -- "$cur") )
        return 0
    fi
    i=2
    while [ "$i" -lt "$COMP_CWORD" ]; do
        case " $_wk_valued " in
            *" ${COMP_WORDS[$i]} "*) i=$((i + 1)) ;;
            *) case "${COMP_WORDS[$i]}" in -*) ;; *) [ -n "$first" ] || first=${COMP_WORDS[$i]}; typed=$((typed + 1)) ;; esac ;;
        esac
        i=$((i + 1))
    done
    case "$cur" in
        -*)
            words=$_wk_flags
            if [ -n "$_wk_vslots" ]; then
                case " $_wk_subverbs " in *" $first "*) verb=$first ;; *) verb=$_wk_default ;; esac
                words=$(_wk_lookup "$_wk_vflags" "$verb")
                words=${words//,/ }
            fi
            COMPREPLY=( $(compgen -W "$words" -- "$cur") )
            return 0 ;;
    esac
    slot=$_wk_slot
    if [ -n "$_wk_vslots" ]; then
        # the workspace's place is the verb's: typed, or the default one a first word stands for
        case " $_wk_subverbs " in *" $first "*) verb=$first ;; *) verb=$_wk_default; shift=1 ;; esac
        slot=$(_wk_lookup "$_wk_vslots" "$verb")
        [ -n "$slot" ] || slot=0
        [ "$slot" -eq 0 ] || slot=$((slot - shift))
    fi
    if [ "$slot" -gt 0 ] && [ "$typed" -eq $((slot - 1)) ]; then
        words=$(PYTHONPATH="$_wk_root/lib" python3 -m wk wk.completion --list-workspaces 2>/dev/null)
    fi
    if [ -n "$_wk_vslots" ]; then
        [ "$typed" -ne 0 ] || words="$words $_wk_subverbs"
        [ "$typed" -ne 1 ] || [ "$shift" -ne 0 ] || [ -z "$_wk_vals" ] || words="$words $(_wk_values "$bin" "$cmd" "$_wk_vals")"
    elif [ -z "$words" ] && [ "$typed" -eq "$_wk_first_arg" ]; then
        words="$_wk_subverbs"
        [ "$_wk_preset" != arg ] || words="$words $_wk_presets"
        [ -z "$_wk_vals" ] || words="$words $(_wk_values "$bin" "$cmd" "$_wk_vals")"
    fi
    COMPREPLY=( $(compgen -W "$words" -- "$cur") )
    return 0
}
_wk_lookup() {
    local r=" $1"
    case "$r" in *" $2:"*) r=${r#* $2:}; printf '%s' "${r%% *}" ;; esac
}
_wk_values() {
    local out
    out=$("$1" "$2" "$3" 2>&1) || return 0
    printf '%s\n' "$out" | awk '!/:$/ && NF { match($0, /^ */); d[NR] = RLENGTH; w[NR] = $1
        if (m == "" || RLENGTH < m) m = RLENGTH } END { for (i = 1; i <= NR; i++) if ((i in d) && d[i] == m) print w[i] }'
}
complete -F _wk_completion wk
'''


def _case_arm(d):
    slot = D.name_slot(d.name_decl)
    flags = flags_for(d)
    vslots = ["%s:%d" % (v, D.name_slot(d.name_for([v]))) for v in subverbs(d)]
    vflags = ["%s:%s" % (v, ",".join(flags_for(d, v))) for v in subverbs(d)]
    return ("        %s) _wk_slot=%d; _wk_first_arg=%d; _wk_flags=%s; _wk_valued=%s; _wk_subverbs=%s; _wk_vslots=%s;"
            " _wk_vflags=%s; _wk_default=%s; _wk_vals=%s; _wk_preset=%s ;;\n"
            % (d.name, slot, 1 if slot == 1 else 0, _words(flags), _words(sorted(d.valued_opts())), _words(subverbs(d)),
               _words(vslots), _words(vflags), _words([d.default]), _words([values_cmd(d)]), _words([d.preset])))


def generate(root, shell_name):
    decls = list(D.all_commands(root))
    out = ["# wk %s completion -- generated by `wk completion %s`; eval this in your rc.\n"
           % (shell_name, shell_name)]
    if shell_name == "zsh":
        # bashcompinit's `complete` calls compdef, which needs compinit (a stock ~/.zshrc omits it); -C reads the dumpfile as it stands.
        out.append("autoload -U +X compinit && compinit -C\n")
        out.append("autoload -U +X bashcompinit && bashcompinit\n")
    out.append("_wk_root=%s\n" % _words([str(root)]))
    out.append("_wk_commands=%s\n" % _words(commands(root)))
    out.append("_wk_presets=%s\n" % _words(presets.names()))
    out.append("_wk_decl() {\n    case \"$1\" in\n")
    for d in decls:
        out.append(_case_arm(d))
    out.append("        completion) _wk_slot=0; _wk_first_arg=0; _wk_flags=''; _wk_valued=''; _wk_subverbs=%s; _wk_vslots='';"
               " _wk_vflags=''; _wk_default=''; _wk_vals=''; _wk_preset='' ;;\n" % _words(SHELLS))
    out.append("        *) return 1 ;;\n    esac\n}\n")
    out.append(_FUNCTION)
    return "".join(out)


def main(argv, env=None):
    """`python3 -m wk.completion --list-workspaces`: the generated script's own far side."""
    root = images.root()
    if argv == ["--list-workspaces"]:
        for name in local_workspaces(root, env):
            print(name)
        return 0
    sys.stderr.write("usage: python3 -m wk.completion --list-workspaces\n")
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
