"""`wk completion bash|zsh` from the declarations; workspace names and `values=` lists are asked at TAB, of this machine only."""

import os
import sys

from wk import images, presets
from wk import decl as D
from wk.places import Registry

BUILTIN_COMMANDS = ("completion",)
SHELLS = ("bash", "zsh")
LOCAL_WHERE = ("local", "host")


def local_workspaces(root, env=None):
    return Registry(root, env).local_workspaces()


def flags_for(d, verb=None):
    specs = [d.opts_for([verb])] if verb else [d.opts] + [spec.get("opts") for _, spec in d.flag]
    return sorted({x.rstrip("=") for spec in specs for x in (spec or "").split(",") if x})


def subverbs(d):
    return sorted(filter(None, d.verbs.split(",")))


def values_cmd(d):
    """The `values=` argument, when the flag it names runs on this machine; a store or workspace one would reach a machine at TAB."""
    if not d.values:
        return ""
    where = d.where
    for flags, spec in d.flag:
        if d.values in flags.split(","):
            where = spec.get("where", where)
    return d.values if where in LOCAL_WHERE else ""


def commands(root):
    return sorted({d.name for d in D.all_commands(root)} | set(BUILTIN_COMMANDS))


def _words(words):
    return "'%s'" % " ".join(words)


FUNCTION = os.path.join(os.path.dirname(os.path.abspath(__file__)), "completion.bash")


def _case_arm(d):
    slot = D.name_slot(d.name_decl)
    flags = flags_for(d)
    vslots = ["%s:%d" % (v, D.name_slot(d.name_for([v]))) for v in subverbs(d)]
    vflags = ["%s:%s" % (v, ",".join(flags_for(d, v))) for v in subverbs(d)]
    return ("        %s) _wk_slot=%d; _wk_first_arg=%d; _wk_flags=%s; _wk_valued=%s; _wk_subverbs=%s; _wk_vslots=%s;"
            " _wk_vflags=%s; _wk_default=%s; _wk_vals=%s; _wk_preset=%s ;;\n"
            % (d.name, slot, 1 if slot == 1 else 0, _words(flags), _words(sorted(d.valued_opts())), _words(subverbs(d)),
               _words(vslots), _words(vflags), _words([d.default]), _words([values_cmd(d)]), _words([d.preset])))


def generate(root, shell_name):
    decls = list(D.all_commands(root))
    out = ["# wk %s completion -- generated by `wk completion %s`; eval this in your rc.\n"
           % (shell_name, shell_name)]
    if shell_name == "zsh":
        # bashcompinit's `complete` calls compdef, which needs compinit (a stock ~/.zshrc omits it); -C reads the dumpfile as it stands.
        out.append("autoload -U +X compinit && compinit -C\n")
        out.append("autoload -U +X bashcompinit && bashcompinit\n")
    out.append("_wk_root=%s\n" % _words([str(root)]))
    out.append("_wk_commands=%s\n" % _words(commands(root)))
    out.append("_wk_presets=%s\n" % _words(presets.names()))
    out.append("_wk_decl() {\n    case \"$1\" in\n")
    for d in decls:
        out.append(_case_arm(d))
    out.append("        completion) _wk_slot=0; _wk_first_arg=0; _wk_flags=''; _wk_valued=''; _wk_subverbs=%s; _wk_vslots='';"
               " _wk_vflags=''; _wk_default=''; _wk_vals=''; _wk_preset='' ;;\n" % _words(SHELLS))
    out.append("        *) return 1 ;;\n    esac\n}\n")
    out.append("\n")
    with open(FUNCTION) as fh:
        out.append(fh.read())
    return "".join(out)


def main(argv, env=None):
    root = images.root()
    if argv == ["--list-workspaces"]:
        for name in local_workspaces(root, env):
            print(name)
        return 0
    sys.stderr.write("usage: python3 -m wk.completion --list-workspaces\n")
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
