"""`wk completion bash|zsh`, generated from the declarations, never `-h` text;
workspace names and `values=` lists are asked at TAB, of this machine only."""

from wk import decl as D
from wk.targets import Registry

BUILTIN_COMMANDS = ("completion",)
SHELLS = ("bash", "zsh")
CONFIG_FLAG, CONFIG_OWNER = "--config", "build"
LOCAL_WHERE = ("local", "host")


def local_workspaces(root, env=None):
    return Registry(root, env).local_workspaces()


def flags_for(d):
    specs = [d.opts] + [spec.get("opts") for _, spec in d.sub + d.flag]
    return sorted({x.rstrip("=") for spec in specs for x in (spec or "").split(",") if x})


def valued_flags(d):
    specs = [d.opts] + [spec.get("opts") for _, spec in d.sub + d.flag]
    return sorted({x[:-1] for spec in specs for x in (spec or "").split(",") if x.endswith("=")})


def subverbs(d):
    return sorted({v for verbs, _ in d.sub for v in verbs.split(",") if not v.startswith("-")})


def values_cmd(d):
    """The `values=` argument, when the flag it names runs on this machine; a store or workspace one would reach a machine at TAB."""
    if not d.values:
        return ""
    where = d.where
    for flags, spec in d.flag:
        if d.values in flags.split(","):
            where = spec.get("where", where)
    return d.values if where in LOCAL_WHERE else ""


def declarations(root, tombstones):
    return [d for d in D.all_commands(root) if d.name not in tombstones]


def commands(root, tombstones):
    return sorted({d.name for d in declarations(root, tombstones)} | set(BUILTIN_COMMANDS))


def _words(words):
    return "'%s'" % " ".join(words)


_FUNCTION = r'''
_wk_completion() {
    local cur prev bin cmd i typed=0 words=
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    bin="${COMP_WORDS[0]}"
    if [ "$COMP_CWORD" -eq 1 ]; then
        COMPREPLY=( $(compgen -W "$_wk_commands" -- "$cur") )
        return 0
    fi
    cmd="${COMP_WORDS[1]}"
    _wk_decl "$cmd" || return 0
    if [ "$prev" = --config ] && [ -n "$_wk_config" ]; then
        COMPREPLY=( $(compgen -W "$(_wk_values "$bin" "$_wk_config_owner" "$_wk_config_values")" -- "$cur") )
        return 0
    fi
    case "$cur" in
        -*) COMPREPLY=( $(compgen -W "$_wk_flags" -- "$cur") ); return 0 ;;
    esac
    i=2
    while [ "$i" -lt "$COMP_CWORD" ]; do
        case " $_wk_valued " in
            *" ${COMP_WORDS[$i]} "*) i=$((i + 1)) ;;
            *) case "${COMP_WORDS[$i]}" in -*) ;; *) typed=$((typed + 1)) ;; esac ;;
        esac
        i=$((i + 1))
    done
    if [ "$_wk_slot" -gt 0 ] && [ "$typed" -eq $((_wk_slot - 1)) ]; then
        words=$("$bin" completion --list-workspaces 2>/dev/null)
    elif [ "$typed" -eq "$_wk_first_arg" ]; then
        words="$_wk_subverbs"
        [ -z "$_wk_vals" ] || words="$words $(_wk_values "$bin" "$cmd" "$_wk_vals")"
    fi
    COMPREPLY=( $(compgen -W "$words" -- "$cur") )
    return 0
}
_wk_values() {
    local out
    out=$("$1" "$2" "$3" 2>&1) || return 0
    printf '%s\n' "$out" | awk '!/:$/ && NF { match($0, /^ */); d[NR] = RLENGTH; w[NR] = $1
        if (m == "" || RLENGTH < m) m = RLENGTH } END { for (i = 1; i <= NR; i++) if ((i in d) && d[i] == m) print w[i] }'
}
complete -F _wk_completion wk
'''


def _case_arm(d, owner_values):
    slot = 0
    if d.name_decl.split("@")[0] in ("required", "optional"):
        slot = int(d.name_decl.split("@")[1]) if "@" in d.name_decl else 1
    flags = flags_for(d)
    return ("        %s) _wk_slot=%d; _wk_first_arg=%d; _wk_flags=%s; _wk_valued=%s; _wk_subverbs=%s; _wk_vals=%s; _wk_config=%s ;;\n"
            % (d.name, slot, 1 if slot == 1 else 0, _words(flags), _words(valued_flags(d)), _words(subverbs(d)),
               _words([values_cmd(d)]), _words(["yes"] if CONFIG_FLAG in flags and owner_values else [])))


def generate(root, shell_name, tombstones):
    decls = declarations(root, tombstones)
    owner = next((d for d in decls if d.name == CONFIG_OWNER), None)
    owner_values = values_cmd(owner) if owner else ""
    out = ["# wk %s completion -- generated by `wk completion %s`; eval this in your rc.\n"
           % (shell_name, shell_name)]
    if shell_name == "zsh":
        # bashcompinit's `complete` calls compdef, which needs compinit (a stock ~/.zshrc omits it); -C reads the dumpfile as it stands.
        out.append("autoload -U +X compinit && compinit -C\n")
        out.append("autoload -U +X bashcompinit && bashcompinit\n")
    out.append("_wk_commands=%s\n" % _words(commands(root, tombstones)))
    out.append("_wk_decl() {\n    _wk_config_owner=%s; _wk_config_values=%s\n    case \"$1\" in\n"
               % (CONFIG_OWNER, owner_values or "''"))
    for d in decls:
        out.append(_case_arm(d, owner_values))
    out.append("        completion) _wk_slot=0; _wk_first_arg=0; _wk_flags=''; _wk_valued=''; _wk_subverbs=%s; _wk_vals=''; _wk_config='' ;;\n"
               % _words(SHELLS))
    out.append("        *) return 1 ;;\n    esac\n}\n")
    out.append(_FUNCTION)
    return "".join(out)
