"""The `Host wk-<name>` block in ~/.ssh/config.d/wk, byte for byte what
lib/target.sh's ssh_alias_set writes and ssh_alias_remove takes out."""

import os

from wk import act
from wk.store import Store

BLOCK = """
Host wk-%s
    # generated by wk -- removed by wk rm
    HostName %s
    User %s
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
%s
"""


def alias_path(env):
    return os.path.join(Store(env).home(), ".ssh", "config.d", "wk")


def _without(text, name):
    kept, skip = [], False
    for line in text.splitlines():
        if line == "Host wk-" + name:
            skip = True
            continue
        if line.startswith("Host "):
            skip = False
        if not skip:
            kept.append(line)
    return "".join(line + "\n" for line in kept)


def _current(machine, conf):
    return machine.read(conf) if machine.exists(conf) else ""


def alias_remove(machine, env, name):
    conf = alias_path(env)
    text = _current(machine, conf)
    if "Host wk-" + name not in text.splitlines():
        return
    machine.write(conf, _without(text, name))


def alias_set(machine, env, name, hostname, user, identity=None, extra=()):
    conf = alias_path(env)
    if not hostname or not user:
        act.die("no address for '%s', so no ssh alias was written: an empty HostName\n"
                "    makes ssh refuse to read %s at all, and with it every other host in it" % (name, conf))
    d = os.path.dirname(conf)
    if not machine.isdir(d):
        machine.mkdir(d)
        if not machine.act_run(["chmod", "0700", d]).ok:
            act.die("cannot set mode 0700 on %s" % d)
    tail = "    IdentityFile %s\n    IdentitiesOnly yes" % identity if identity else ""
    for line in extra:
        tail += "\n    " + line
    text = _without(_current(machine, conf), name)
    machine.write(conf, text + BLOCK % (name, hostname, user, tail))
